# fly.toml app configuration file generated for runalyze-mcp-server
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
# This HTTP server requires Bearer token authentication.
# Users must include their Runalyze API token in the Authorization header:
# Authorization: Bearer <your-runalyze-token>

app = 'runalyze-mcp-server'
primary_region = 'ams'

[build]

[deploy]
  strategy = 'immediate'

[env]
  PORT = '3000'
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    grace_period = '10s'
    interval = '30s'
    method = 'GET'
    timeout = '5s'
    path = '/health'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
